# Generated by Django 6.0.8 on 2026-08-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_address_remove_profile_blocked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
