# Generated by Django 6.0.8 on 2026-08-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_certificate_evaluation_task_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
