# Generated by Django 6.0.8 on 2026-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_title_alter_task_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_qr/'),
        ),
    ]
