# Generated by Django 6.0.8 on 2026-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill_category_skill_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='violation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('text', 'text'), ('code', 'code')], default='text', max_length=10),
        ),
    ]
