# Generated by Django 6.0.8 on 2026-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_assessment_violation_reason_task_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='integrity_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
