# Generated by Django 6.0.8 on 2026-08-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_assessment_audit_trail_assessment_integrity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='submission_type',
            field=models.CharField(default='Manual Submission', max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='duration',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
